---
# Setup core system/user credentials

# First we'll grap 1password CLI and set it up
#- pause:
#    prompt: "Please enter the 1password secret key"
#    echo: yes
#  register: result
#- set_fact:
#    op_secret: "{{ result.user_input }}"
#- debug:
#    var: op_secret
#
#- pause:
#    prompt: "Please enter the 1password master password"
#    echo: yes
#  register: result2
#- set_fact:
#    op_pass: "{{ result2.user_input }}"
#- debug:
#    var: op_pass

- name: create temporary install directory
  tempfile:
    state: directory
    suffix: build
  register: tmpdir
- debug:
    var: tmpdir

- name: Download 1password client
  get_url:
    url: https://cache.agilebits.com/dist/1P/op/pkg/v0.10.0/op_linux_amd64_v0.10.0.zip
    dest: "{{tmpdir.path}}/op.zip"
    mode: '0440'

- name: unpack 1password client
  command: "unzip -o {{tmpdir.path}}/op.zip -d /usr/local/bin/"

#- name: verify 2password cli binary
#  command: "gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 4FEF9748469ADBE15DA7CA80AC2D62742012EA22"

- name: verify 2password cli binary
  command: "gpg --verify /usr/local/bin/op.sig /usr/local/bin/op"
