- name: setup user credentials
  include: credentials.yml

- name: mount system LVM volumes
  include: volumes.yml

- name: setup KVM
  include: kvm.yml

- name: include and run software/package tasks
  include: software.yml

- name: include and run firewall tasks
  include: firewall.yml

## STABLILITY/HARDENING/SECURITY
- name: Add additional nameserver '1.1.1.1' to /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver 1.1.1.1

#- name: remove OS information leak from postfix
#  replace:
#    path: /etc/postfix/main.cf
#    regexp: '\ \$mail_name \(Ubuntu\)'
#    replace: ''

- name: only root should read cupsd config
  file:
    path: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: '0600'

#- name: disable postfix VRFY command
#  shell: postconf -e disable_vrfy_command=yes

